# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c3edc0e1-91f3-4c16-ad48-7bb1674c1ced";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E94C-A52E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };


  # ====== SHARED DRIVES CONFIGURATION ======
  systemd.tmpfiles.rules = [
    "d /shared 0755 root users -"
    "d /shared/Garnet 0755 root users -"
    "d /shared/Pearl 0755 root users -"
  ];

  fileSystems."/shared/Garnet" = {
    device = "/dev/disk/by-uuid/bf49a367-83dd-4d9c-ab5b-5aaa29906569";
    fsType = "ext4";
    options = [ "nofail" "x-gvfs-show" "rw" ];
  };

  fileSystems."/shared/Pearl" = {
    device = "/dev/disk/by-uuid/d6dce8f5-8c8e-4088-b697-cf7016618972";
    fsType = "btrfs";
    options = [ "nofail" "x-gvfs-show" "rw" ];
  };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/8c3d9c29-52e3-451a-8301-083bc291bfdd"; 
    }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
